name: Size Changes

on:
  workflow_call:
    inputs:
      input:
        description: 'input'
        required: true
        type: string
  workflow_run:
    workflows:
      - Test
    branches:
      - 'test-workflow'
    types:
      - completed

jobs:
  other:
    runs-on: ubuntu-latest
    changes: ${{ fromJSON(inputs.input) }}
    steps:
    - name: Check
      run: |
        {
          echo '```yml'
          echo 'inputs.input: ${{ inputs.input }}'
          echo 'inputs.output: ${{ inputs.output }}'
          echo 'github.event.inputs.input: ${{ github.event.inputs.input }}'
          echo 'github.event.inputs.output: ${{ github.event.inputs.output }}'
          echo '```'
        } | tee -a "$GITHUB_STEP_SUMMARY"
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ changes }}
      run: |
        echo "$GITHUB_CONTEXT"
  size-storage:
    name: Store New functions size
    runs-on: ubuntu-latest
    #container:
    #  image: ghcr.io/viamrobotics/micro-rdk-dev-env:amd64
    timeout-minutes: 20
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github.event.workflow_run.jobs) }}
      run: |
        echo "$GITHUB_CONTEXT"
    - name: YTY
      uses: actions/github-script@v7
      with:
        script: |
          console.log(context)
          const diff_url = context.payload.workflow_run.jobs_url
          const result = await github.request(diff_url)
          console.log(result.data.jobs[0])
    - name : Checkout main branch code
      if: github.event_name != 'pull_request_target'
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Install cargo-bloat
      run: |
        cargo binstall cargo-bloat -y
    - name: Calc Sizes
      run: |
        bash -c '. /home/testbot/.bash_profile ; git config --global --add safe.directory "$ESP_ROOT"/esp-idf && make clippy-esp32'
        bash -c '. /home/testbot/.bash_profile ; cd micro-rdk-server && cd ../ && make make-size-summary > /tmp/sizes.json'
    - name: Archive code size
      uses: actions/upload-artifact@v4
      with:
        name: functions-size-micro-rdk
        path: /tmp/sizes.json
